# Generated by Django 3.2 on 2023-05-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#FFA500', 'Оранжевый'), ('#008000', 'Зеленый'), ('#FFFF00', 'Желтый'), ('#0000FF', 'Синий')], default='#0000FF', max_length=7, unique=True, verbose_name='Цвет'),
        ),
    ]
